// <auto-generated />
using System;
using Infraestructura.ContextoPrincipal.UnidadDeTrabajo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infraestructura.ContextoPrincipal.Migrations
{
    [DbContext(typeof(UnidadTrabajo))]
    [Migration("20210106163112_Columna Posicion Comparecientes")]
    partial class ColumnaPosicionComparecientes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dominio.ContextoPrincipal.Entidad.Parametricas.Categoria", b =>
                {
                    b.Property<long>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categorias","Parametricas");
                });

            modelBuilder.Entity("Dominio.ContextoPrincipal.Entidad.Parametricas.Colaborador", b =>
                {
                    b.Property<long>("ColaboradorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Cargo")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("NotariaId")
                        .HasColumnType("bigint");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ColaboradorId");

                    b.HasIndex("NotariaId");

                    b.ToTable("Colaboradores","Parametricas");
                });

            modelBuilder.Entity("Dominio.ContextoPrincipal.Entidad.Parametricas.ConvenioRNEC", b =>
                {
                    b.Property<long>("ConvenioRNECId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Convenio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint");

                    b.Property<long>("IdOficina")
                        .HasColumnType("bigint");

                    b.Property<long>("IdRol")
                        .HasColumnType("bigint");

                    b.Property<long>("IdZona")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("NotariaId")
                        .HasColumnType("bigint");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConvenioRNECId");

                    b.HasIndex("NotariaId");

                    b.ToTable("ConveniosRNEC","Parametricas");
                });

            modelBuilder.Entity("Dominio.ContextoPrincipal.Entidad.Parametricas.EstadoTramite", b =>
                {
                    b.Property<long>("EstadoTramiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstadoTramiteId");

                    b.ToTable("EstadosTramites","Parametricas");
                });

            modelBuilder.Entity("Dominio.ContextoPrincipal.Entidad.Parametricas.Maquina", b =>
                {
                    b.Property<long>("MaquinaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DireccionIP")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MAC")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<long>("NotariaId")
                        .HasColumnType("bigint");

                    b.Property<int>("TipoMaquina")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaquinaId");

                    b.HasIndex("NotariaId");

                    b.ToTable("Maquinas","Parametricas");
                });

            modelBuilder.Entity("Dominio.ContextoPrincipal.Entidad.Parametricas.Notaria", b =>
                {
                    b.Property<long>("NotariaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CirculoNotaria")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<int>("NumeroNotaria")
                        .HasColumnType("int");

                    b.Property<string>("NumeroNotariaEnLetras")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("Sello")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<long>("UbicacionId")
                        .HasColumnType("bigint");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NotariaId");

                    b.HasIndex("UbicacionId");

                    b.ToTable("Notarias","Parametricas");
                });

            modelBuilder.Entity("Dominio.ContextoPrincipal.Entidad.Parametricas.NotariaUsuarios", b =>
                {
                    b.Property<long>("NotariaUsuariosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("NotariaId")
                        .HasColumnType("bigint");

                    b.Property<long>("PersonaId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SincronizoRNEC")
                        .HasColumnType("bit");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuariosId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NotariaUsuariosId");

                    b.HasIndex("IsDeleted")
                        .HasAnnotation("SqlServer:Include", new[] { "UsuariosId" });

                    b.HasIndex("NotariaId");

                    b.HasIndex("PersonaId");

                    b.HasIndex("UserEmail");

                    b.HasIndex("IsDeleted", "UserEmail");

                    b.ToTable("NotariasUsuario","Parametricas");
                });

            modelBuilder.Entity("Dominio.ContextoPrincipal.Entidad.Parametricas.Notario", b =>
                {
                    b.Property<long>("NotarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Grafo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<long>("NotariaUsuariosId")
                        .HasColumnType("bigint");

                    b.Property<string>("Pin")
                        .HasColumnType("nvarchar(6)")
                        .HasMaxLength(6);

                    b.Property<int>("TipoNotario")
                        .HasColumnType("int");

                    b.Property<bool>("UsarSticker")
                        .HasColumnType("bit");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NotarioId");

                    b.HasIndex("NotariaUsuariosId")
                        .IsUnique();

                    b.ToTable("Notarios","Parametricas");
                });

            modelBuilder.Entity("Dominio.ContextoPrincipal.Entidad.Parametricas.Parametrica", b =>
                {
                    b.Property<long>("ParametricaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Expresion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Longitud")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.HasKey("ParametricaId");

                    b.ToTable("Parametricas","Parametricas");
                });

            modelBuilder.Entity("Dominio.ContextoPrincipal.Entidad.Parametricas.Persona", b =>
                {
                    b.Property<long>("PersonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(120)")
                        .HasMaxLength(120);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(512)")
                        .HasMaxLength(512);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("NumeroCelular")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("TipoIdentificacionId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tokenAuth")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonaId");

                    b.HasIndex("TipoIdentificacionId", "NumeroDocumento")
                        .IsUnique();

                    b.ToTable("Personas","Parametricas");
                });

            modelBuilder.Entity("Dominio.ContextoPrincipal.Entidad.Parametricas.PersonaDatos", b =>
                {
                    b.Property<long>("PersonaDatosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("PersonaId")
                        .HasColumnType("bigint");

                    b.Property<int>("TipoDatoId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorDato")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("PersonaDatosId");

                    b.HasIndex("PersonaId");

                    b.HasIndex("TipoDatoId");

                    b.ToTable("PersonasDatos","Parametricas");
                });

            modelBuilder.Entity("Dominio.ContextoPrincipal.Entidad.Parametricas.PlantillaActa", b =>
                {
                    b.Property<long>("PlantillaActaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlantillaActaId");

                    b.ToTable("PlantillasActas","Parametricas");
                });

            modelBuilder.Entity("Dominio.ContextoPrincipal.Entidad.Parametricas.TipoDato", b =>
                {
                    b.Property<int>("TipoDatoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.HasKey("TipoDatoId");

                    b.ToTable("TiposDatos","Parametricas");

                    b.HasData(
                        new
                        {
                            TipoDatoId = 1,
                            Nombre = "Direccion"
                        },
                        new
                        {
                            TipoDatoId = 2,
                            Nombre = "NumeroCelular"
                        },
                        new
                        {
                            TipoDatoId = 3,
                            Nombre = "Email"
                        });
                });

            modelBuilder.Entity("Dominio.ContextoPrincipal.Entidad.Parametricas.TipoIdentificacion", b =>
                {
                    b.Property<int>("TipoIdentificacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abreviatura")
                        .HasColumnType("nvarchar(3)")
                        .HasMaxLength(3);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoIdentificacionId");

                    b.ToTable("TiposIdentificacion","Parametricas");
                });

            modelBuilder.Entity("Dominio.ContextoPrincipal.Entidad.Parametricas.TipoTramite", b =>
                {
                    b.Property<long>("TipoTramiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CategoriaId")
                        .HasColumnType("bigint");

                    b.Property<long>("CodigoTramite")
                        .HasColumnType("bigint");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<long>("PlantillaActaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PlantillaStickerId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductoReconoserId")
                        .HasColumnType("bigint");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoTramiteId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("PlantillaActaId");

                    b.HasIndex("PlantillaStickerId");

                    b.ToTable("TiposTramites","Parametricas");
                });

            modelBuilder.Entity("Dominio.ContextoPrincipal.Entidad.Parametricas.Ubicacion", b =>
                {
                    b.Property<long>("UbicacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UbicacionPadreId")
                        .HasColumnType("bigint");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UbicacionId");

                    b.HasIndex("UbicacionPadreId");

                    b.ToTable("Ubicaciones","Parametricas");
                });

            modelBuilder.Entity("Dominio.ContextoPrincipal.Entidad.Transaccional.Archivo", b =>
                {
                    b.Property<long>("ArchivoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Contenido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("MetadataArchivoId")
                        .HasColumnType("bigint");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArchivoId");

                    b.HasIndex("MetadataArchivoId")
                        .IsUnique();

                    b.ToTable("Archivos","Transaccional");
                });

            modelBuilder.Entity("Dominio.ContextoPrincipal.Entidad.Transaccional.Compareciente", b =>
                {
                    b.Property<long>("ComparecienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<long>("FirmaId")
                        .HasColumnType("bigint");

                    b.Property<long>("FotoId")
                        .HasColumnType("bigint");

                    b.Property<long>("ImagenDocumentoId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MotivoSinBiometria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PersonaId")
                        .HasColumnType("bigint");

                    b.Property<string>("PeticionRNEC")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(36)")
                        .HasMaxLength(36)
                        .HasDefaultValue("");

                    b.Property<int?>("Posicion")
                        .HasColumnType("int");

                    b.Property<long>("TramiteId")
                        .HasColumnType("bigint");

                    b.Property<bool>("TramiteSinBiometria")
                        .HasColumnType("bit");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ComparecienteId");

                    b.HasIndex("FirmaId")
                        .IsUnique();

                    b.HasIndex("FotoId")
                        .IsUnique();

                    b.HasIndex("ImagenDocumentoId")
                        .IsUnique();

                    b.HasIndex("PersonaId");

                    b.HasIndex("TramiteId");

                    b.ToTable("Comparecientes","Transaccional");
                });

            modelBuilder.Entity("Dominio.ContextoPrincipal.Entidad.Transaccional.ExcepcionHuella", b =>
                {
                    b.Property<long>("ExcepcionHuellaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ComparecienteId")
                        .HasColumnType("bigint");

                    b.Property<int>("DedosExceptuados")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExcepcionHuellaId");

                    b.HasIndex("ComparecienteId")
                        .IsUnique();

                    b.ToTable("ExcepcionesHuellas","Transaccional");
                });

            modelBuilder.Entity("Dominio.ContextoPrincipal.Entidad.Transaccional.MetadataArchivo", b =>
                {
                    b.Property<long>("MetadataArchivoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Ruta")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<long>("Tamanio")
                        .HasColumnType("bigint");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MetadataArchivoId");

                    b.ToTable("MetadataArchivos","Transaccional");
                });

            modelBuilder.Entity("Dominio.ContextoPrincipal.Entidad.Transaccional.Tramite", b =>
                {
                    b.Property<long>("TramiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("ActaNotarialId")
                        .HasColumnType("bigint");

                    b.Property<int>("CantidadComparecientes")
                        .HasColumnType("int");

                    b.Property<string>("DatosAdicionales")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("EstadoTramiteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("NotariaId")
                        .HasColumnType("bigint");

                    b.Property<long>("TipoTramiteId")
                        .HasColumnType("bigint");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TramiteId");

                    b.HasIndex("ActaNotarialId")
                        .IsUnique()
                        .HasFilter("[ActaNotarialId] IS NOT NULL");

                    b.HasIndex("EstadoTramiteId");

                    b.HasIndex("NotariaId");

                    b.HasIndex("TipoTramiteId");

                    b.HasIndex("IsDeleted", "NotariaId");

                    b.HasIndex("IsDeleted", "NotariaId", "EstadoTramiteId")
                        .HasAnnotation("SqlServer:Include", new[] { "TramiteId", "FechaCreacion", "CantidadComparecientes", "TipoTramiteId" });

                    b.HasIndex("IsDeleted", "NotariaId", "FechaCreacion");

                    b.HasIndex("IsDeleted", "NotariaId", "EstadoTramiteId", "FechaCreacion")
                        .HasAnnotation("SqlServer:Include", new[] { "TramiteId", "CantidadComparecientes", "TipoTramiteId" });

                    b.ToTable("Tramites","Transaccional");
                });

            modelBuilder.Entity("Dominio.ContextoPrincipal.Entidad.Parametricas.Colaborador", b =>
                {
                    b.HasOne("Dominio.ContextoPrincipal.Entidad.Parametricas.Notaria", "Notaria")
                        .WithMany("Colaboradores")
                        .HasForeignKey("NotariaId")
                        .HasConstraintName("FK_Colaboradores_Notarias")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.ContextoPrincipal.Entidad.Parametricas.ConvenioRNEC", b =>
                {
                    b.HasOne("Dominio.ContextoPrincipal.Entidad.Parametricas.Notaria", "Notaria")
                        .WithMany()
                        .HasForeignKey("NotariaId")
                        .HasConstraintName("FK_ConveniosRNEC_Notarias")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.ContextoPrincipal.Entidad.Parametricas.Maquina", b =>
                {
                    b.HasOne("Dominio.ContextoPrincipal.Entidad.Parametricas.Notaria", "Notaria")
                        .WithMany()
                        .HasForeignKey("NotariaId")
                        .HasConstraintName("FK_Maquinas_Notarias")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.ContextoPrincipal.Entidad.Parametricas.Notaria", b =>
                {
                    b.HasOne("Dominio.ContextoPrincipal.Entidad.Parametricas.Ubicacion", "Ubicacion")
                        .WithMany()
                        .HasForeignKey("UbicacionId")
                        .HasConstraintName("FK_Notarias_Ubicaciones")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.ContextoPrincipal.Entidad.Parametricas.NotariaUsuarios", b =>
                {
                    b.HasOne("Dominio.ContextoPrincipal.Entidad.Parametricas.Notaria", "Notaria")
                        .WithMany("NotariasUsuarios")
                        .HasForeignKey("NotariaId")
                        .HasConstraintName("FK_NotariasUsuarios_Notarias")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dominio.ContextoPrincipal.Entidad.Parametricas.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .HasConstraintName("FK_NotariasUsuarios_Personas")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.ContextoPrincipal.Entidad.Parametricas.Notario", b =>
                {
                    b.HasOne("Dominio.ContextoPrincipal.Entidad.Parametricas.NotariaUsuarios", "NotariaUsuarios")
                        .WithOne("Notario")
                        .HasForeignKey("Dominio.ContextoPrincipal.Entidad.Parametricas.Notario", "NotariaUsuariosId")
                        .HasConstraintName("FK_Notarios_NotariasUsuarios")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.ContextoPrincipal.Entidad.Parametricas.Persona", b =>
                {
                    b.HasOne("Dominio.ContextoPrincipal.Entidad.Parametricas.TipoIdentificacion", "TipoIdentificacion")
                        .WithMany()
                        .HasForeignKey("TipoIdentificacionId")
                        .HasConstraintName("FK_TipoIdentificacion_Personas")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.ContextoPrincipal.Entidad.Parametricas.PersonaDatos", b =>
                {
                    b.HasOne("Dominio.ContextoPrincipal.Entidad.Parametricas.Persona", "Persona")
                        .WithMany("PersonaDatos")
                        .HasForeignKey("PersonaId")
                        .HasConstraintName("FK_PersonaDatos_Personas")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dominio.ContextoPrincipal.Entidad.Parametricas.TipoDato", "TipoDato")
                        .WithMany()
                        .HasForeignKey("TipoDatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.ContextoPrincipal.Entidad.Parametricas.TipoTramite", b =>
                {
                    b.HasOne("Dominio.ContextoPrincipal.Entidad.Parametricas.Categoria", "Categoria")
                        .WithMany("TiposTramites")
                        .HasForeignKey("CategoriaId")
                        .HasConstraintName("FK_TiposTramites_Categorias")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dominio.ContextoPrincipal.Entidad.Parametricas.PlantillaActa", "PlantillaActa")
                        .WithMany("TiposTramites")
                        .HasForeignKey("PlantillaActaId")
                        .HasConstraintName("FK_TiposTramites_PlantillasActas")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Dominio.ContextoPrincipal.Entidad.Parametricas.PlantillaActa", "PlantillaSticker")
                        .WithMany()
                        .HasForeignKey("PlantillaStickerId")
                        .HasConstraintName("FK_TiposTramites_PlantillasStickers")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Dominio.ContextoPrincipal.Entidad.Parametricas.Ubicacion", b =>
                {
                    b.HasOne("Dominio.ContextoPrincipal.Entidad.Parametricas.Ubicacion", "UbicacionPadre")
                        .WithMany("UbicacionesHijo")
                        .HasForeignKey("UbicacionPadreId")
                        .HasConstraintName("FK_Ubicacion_UbicacionPadre")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Dominio.ContextoPrincipal.Entidad.Transaccional.Archivo", b =>
                {
                    b.HasOne("Dominio.ContextoPrincipal.Entidad.Transaccional.MetadataArchivo", "MetadataArchivo")
                        .WithOne("Archivo")
                        .HasForeignKey("Dominio.ContextoPrincipal.Entidad.Transaccional.Archivo", "MetadataArchivoId")
                        .HasConstraintName("FK_Archivos_MetadataArchivos")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.ContextoPrincipal.Entidad.Transaccional.Compareciente", b =>
                {
                    b.HasOne("Dominio.ContextoPrincipal.Entidad.Transaccional.MetadataArchivo", "Firma")
                        .WithOne()
                        .HasForeignKey("Dominio.ContextoPrincipal.Entidad.Transaccional.Compareciente", "FirmaId")
                        .HasConstraintName("FK_Firmas_Comparecientes")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dominio.ContextoPrincipal.Entidad.Transaccional.MetadataArchivo", "Foto")
                        .WithOne()
                        .HasForeignKey("Dominio.ContextoPrincipal.Entidad.Transaccional.Compareciente", "FotoId")
                        .HasConstraintName("FK_Fotos_Comparecientes")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dominio.ContextoPrincipal.Entidad.Transaccional.MetadataArchivo", "ImagenDocumento")
                        .WithOne()
                        .HasForeignKey("Dominio.ContextoPrincipal.Entidad.Transaccional.Compareciente", "ImagenDocumentoId")
                        .HasConstraintName("FK_ImagenesDocumento_Comparecientes")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dominio.ContextoPrincipal.Entidad.Parametricas.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .HasConstraintName("FK_Personas_Comparecientes")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dominio.ContextoPrincipal.Entidad.Transaccional.Tramite", "Tramite")
                        .WithMany("Comparecientes")
                        .HasForeignKey("TramiteId")
                        .HasConstraintName("FK_Comparecientes_Tramites")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.ContextoPrincipal.Entidad.Transaccional.ExcepcionHuella", b =>
                {
                    b.HasOne("Dominio.ContextoPrincipal.Entidad.Transaccional.Compareciente", "Compareciente")
                        .WithOne("ExcepcionHuella")
                        .HasForeignKey("Dominio.ContextoPrincipal.Entidad.Transaccional.ExcepcionHuella", "ComparecienteId")
                        .HasConstraintName("FK_ExcepcionesHuellas_Comparecientes")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.ContextoPrincipal.Entidad.Transaccional.Tramite", b =>
                {
                    b.HasOne("Dominio.ContextoPrincipal.Entidad.Transaccional.MetadataArchivo", "ActaNotarial")
                        .WithOne()
                        .HasForeignKey("Dominio.ContextoPrincipal.Entidad.Transaccional.Tramite", "ActaNotarialId")
                        .HasConstraintName("FK_Tramites_MetadataActaNotarial")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Dominio.ContextoPrincipal.Entidad.Parametricas.EstadoTramite", "EstadoTramite")
                        .WithMany()
                        .HasForeignKey("EstadoTramiteId")
                        .HasConstraintName("FK_Tramites_EstadosTramites")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dominio.ContextoPrincipal.Entidad.Parametricas.Notaria", "Notaria")
                        .WithMany()
                        .HasForeignKey("NotariaId")
                        .HasConstraintName("FK_Tramites_Notarias")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dominio.ContextoPrincipal.Entidad.Parametricas.TipoTramite", "TipoTramite")
                        .WithMany()
                        .HasForeignKey("TipoTramiteId")
                        .HasConstraintName("FK_Tramites_TiposTramites")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
