//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura.Transversal.Mensaje {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Recursos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recursos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infraestructura.Transversal.Mensaje.Recursos", typeof(Recursos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al adicionar {0}.
        /// </summary>
        internal static string Aplicacion_exception_ErrorAdiconarEntidad {
            get {
                return ResourceManager.GetString("Aplicacion_exception_ErrorAdiconarEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor verifique ValidationErros para mas informacion.
        /// </summary>
        internal static string Aplicacion_validation_Exception {
            get {
                return ResourceManager.GetString("Aplicacion_validation_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede adiconar una Empresa. el objeto esta vacio..!.
        /// </summary>
        internal static string Aplicacion_warning_adicionarempresamodelnull {
            get {
                return ResourceManager.GetString("Aplicacion_warning_adicionarempresamodelnull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha especificaco la fabrica para Correo.
        /// </summary>
        internal static string Excepcion_CorreoFactory {
            get {
                return ResourceManager.GetString("Excepcion_CorreoFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha especificado la fabrica de Serilog.
        /// </summary>
        internal static string Excepcion_SerilogFactory {
            get {
                return ResourceManager.GetString("Excepcion_SerilogFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha especificaco la fabrica para el Adaptador.
        /// </summary>
        internal static string Excepcion_TipoAdaptador {
            get {
                return ResourceManager.GetString("Excepcion_TipoAdaptador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es valido el enumerador.
        /// </summary>
        internal static string Infraestructura_exception_InvalidoTipoEnumeracion {
            get {
                return ResourceManager.GetString("Infraestructura_exception_InvalidoTipoEnumeracion", resourceCulture);
            }
        }
    }
}
